//
// Created by Haswell on 22/05/2020.
//

#ifndef SCHEDULER_CONSTANTS_H
#define SCHEDULER_CONSTANTS_H

#define FIRST_COME_FIRST_SERVED 1
#define ROUND_ROBIN 2
#define CUSTOMISED_SCHEDULING 3

#define UNLIMITED -1
#define SWAPPING -2
#define VIRTUAL_MEMORY -3
#define CUSTOMISED_MEMORY -4
//#define LOG_LEVEL LOG_INFO
#define LOG_LEVEL LOG_DEBUG
//#define LOG_LEVEL LOG_TRACE
//#define LOG_LEVEL LOG_WARN

#define PAGE_SIZE 4
#define HOLE_FRAGMENT 5
#define PROCESS_FRAGMENT 6
#define LOADING_TIME_PER_PAGE 2

#endif //SCHEDULER_CONSTANTS_H
